import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar.jsx'
import FooterComponent from '@/components/FooterComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar></NavBar>
        <div className="p-0 mb-10 min-h-screen ">
        {children}
      </div>
        <FooterComponent></FooterComponent>
      </body>

    </html>
  )
}
